name: PDF creation

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        slides-markdown: [['version-control/material/intro_slides.md','version-control-intro-slides.pdf'], ['organization/material/rse_basics.md','organization-rse-basics.pdf'], ['organization/material/intro_course.md','organization-intro-course.pdf'], ['organization/material/challenge_intro.md','organization-challenge-intro.pdf']]
        text-markdown: [ ['version-control/material/git_quiz.md','version-control-git-quiz.pdf'] ]
    steps:
      - uses: actions/checkout@v2

      - name: create file list
        id: files_list
        run: |
          mkdir slides
#          echo "::set-output name=files::$(printf '"%s" ' *.md)"

      - uses: docker://pandoc/latex:latest
        with:
          args: >-
            -t beamer
            -V aspectratio=169
            -V linkcolor:blue
            -V fontsize=12pt
            --listings
            -s
            --output=slides/${{ matrix.slides-markdown[1] }}
            ${{ matrix.slides-markdown[0] }}

      - uses: docker://pandoc/latex:latest
        with:
          args: >-
            -V geometry:a4paper
            -V geometry:left=2.5cm
            -V geometry:right=2.5cm
            -V geometry:bottom=2.5cm
            -V geometry:top=2.5cm
            -V linkcolor:blue
            -V fontsize=10pt
            --listings
            --output=slides/${{ matrix.text-markdown[1] }}
            ${{ matrix.text-markdown[0] }}

      - uses: actions/upload-artifact@master
        with:
          name: slides
          path: slides