name: Create PDF of slides via pandoc

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: create file list
        id: files_list
        run: |
          mkdir slides
#          echo "::set-output name=files::$(printf '"%s" ' *.md)"

      - uses: docker://pandoc/latex:latest
        with:
          args: >-
            -t beamer
            -V aspectratio=169
            -V linkcolor:blue
            -V fontsize=12pt
            -s
            --output=slides/version-control-intro-slides.pdf
            version-control/material/intro_slides.md

      - uses: docker://pandoc/latex:latest
        with:
          args: >-
            -t beamer
            -V aspectratio=169
            -V linkcolor:blue
            -V fontsize=12pt
            -s
            --output=slides/version-control-git-quiz.pdf
            version-control/material/git_quiz.md

      - uses: docker://pandoc/latex:latest
        with:
          args: >-
            -t beamer
            -V aspectratio=169
            -V linkcolor:blue
            -V fontsize=12pt
            -s
            --output=slides/organization-rse-basics.pdf
            organization/material/rse_basics.md

      - uses: docker://pandoc/latex:latest
        with:
          args: >-
            -t beamer
            -V aspectratio=169
            -V linkcolor:blue
            -V fontsize=12pt
            -s
            --output=slides/organization-intro-course.pdf
            organization/material/intro_course.md

      - uses: docker://pandoc/latex:latest
        with:
          args: >-
            -t beamer
            -V aspectratio=169
            -V linkcolor:blue
            -V fontsize=12pt
            -s
            --output=slides/organization-challenge-intro.pdf
            organization/material/challenge_intro.md

      - uses: actions/upload-artifact@master
        with:
          name: slides
          path: slides