name: PDF creation

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  create_slides:
    runs-on: ubuntu-20.04
    container: pandoc/latex:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Compile PDFs (slides)
        run: |
          ./scripts/create-slides.sh
      - uses: actions/upload-artifact@master
        with:
          name: slides
          path: slides

  create_texts:
    runs-on: ubuntu-20.04
    container: pandoc/latex:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Compile PDFs (texts)
        run: |
          ./scripts/create-texts.sh
      - uses: actions/upload-artifact@master
        with:
          name: texts
          path: texts